name: socket_io_client
description: Dartlang port of socket.io-client
version: 0.8.2
author: jumperchen <jumperchen@potix.com>
homepage: https://www.zkoss.org

environment:
  sdk: '>=1.0.0'

dependencies:
  logging: '>=0.11.3+1 <0.12.0'
  socket_io: any

dev_dependencies:
  unittest: any
  browser: any
  test: '>=0.12.0 <0.13.0'
