name: socket_io_client
description: Dartlang port of socket.io-client for web, flutter, dartvm to use
version: 0.9.10+1
homepage: https://www.zkoss.org
repository: https://github.com/rikulo/socket.io-client-dart
issue_tracker: https://github.com/rikulo/socket.io-client-dart/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  logging: ^0.11.3+2
  socket_io_common: ">=0.9.2 <2.0.0"

dev_dependencies:
  test: ">=1.3.0 <2.0.0"
  build_runner: any
  build_web_compilers: any
  socket_io: any
  pedantic: ^1.9.0

  
